-- RETIRED. Stripe Connect is no longer used.
-- Client payments are collected on the By Excellence Stripe account.
-- Provider settlement is an in-app bank-transfer order (provider_payouts).
--
-- Existing databases may already have these unused columns:
--   providers.stripe_account_id
--   providers.stripe_connect_status
--   providers.stripe_payouts_enabled
--   providers.stripe_connect_requested_at
-- Do not DROP them, and do not run the old ALTER that added them.
-- New installs (schema.sql) do not create them.
